/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UTS_22090120_KarelTrisnantoUtomo_C;

public class App {
    public static void main(String[] args) {
        new MainApp().setVisible(true);
    }
}
